image: blurri/meteor-node-heroku

variables:
    METEOR_ALLOW_SUPERUSER: "true"

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: ./test.sh

build:
  stage: build
  script: ./build-staging.sh
  only:
  - develop

deploy_staging:
  stage: deploy
  script: ./deploy-staging.sh
  environment:
    name: staging
    url: https://gba-mantra-boilerplate.herokuapp.com
  only:
  - develop