image: blurri/meteor-node
variables:
    METEOR_ALLOW_SUPERUSER: "true"
test:
  script:
   - cd app
   - meteor npm install
   - meteor npm run lint
   - meteor npm run ci


image: blurri/meteor-node
variables:
    METEOR_ALLOW_SUPERUSER: "true"

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: ./test.sh

build:
  stage: build
  script: ./build-staging.sh
  artifacts:
    paths:
    - build
  only:
  - develop

deploy_staging:
  stage: deploy
  script:
    - heroku git:remote -a gba-mantra-boilerplate
    - git subtree push --prefix app heroku master
  environment:
    name: staging
    url: https://gba-mantra-boilerplate.herokuapp.com
  only:
  - develop